// 
// Decompiled by Procyon v0.5.30
// 

package entity;

public class UM_GOE_ConiC090b
{
    public String[] sender;
    public String[] receiver;
    public String[] messFunc;
    public String[] messCode;
    public String[] messName;
    public String[] messVersion;
    public String[] messNum;
    public String[] manageNum;
    public String[] referNum;
    public String[] title;
    public String[] saupNo;
    public String[] nationality;
    public String[] sangho;
    public String[] eSangho;
    public String[] openDate;
    public String[] bubinOpenDate;
    public String[] jobGubun;
    public String[] makeGubun;
    public String[] dpUpjongCode;
    public String[] bubinNo;
    public String[] comGubun1;
    public String[] comGubun2;
    public String[] comGubunYear;
    public String[] jabon;
    public String[] employeeNo;
    public String[] accountDate;
    public String[] zipCode;
    public String[] localCode;
    public String[] addr;
    public String[] restAddr;
    public String[] tel;
    public String[] fax;
    public String[] homepage;
    public String[] exceptYN;
    public String[] registOkDate;
    public String[] registDate;
    public String[] renewDate;
    public String[] dpOkYN;
    public String[] seq1;
    public String[] licenseNo;
    public String[] licenseCode;
    public String[] licenseBeginDate;
    public String[] licenseEndDate;
    public String[] sigongAccount;
    public String[] peonggaYear;
    public String[] dpLicenseYN;
    public String[] seq2;
    public String[] ceoJuminNo;
    public String[] ceoName;
    public String[] ceoMail;
    public String[] ceoYN;
    public String[] ilrunNo;
    public String[] factoryName;
    public String[] factoryZipCode;
    public String[] factoryAddr;
    public String[] factoryRestAddr;
    public String[] factoryTel;
    public String[] factoryFax;
    public String[] seq3;
    public String[] juminNo;
    public String[] name;
    public String[] jobPart;
    public String[] dutyName;
    public String[] tel3;
    public String[] mail;
    public String[] handphone;
    public String[] fax3;
    public String[] seq4;
    public String[] goodsNo;
    public String[] formNo;
    public String[] formOrg;
    public String[] formDate;
    public String[] threeSale;
    public String[] makeYN;
    public String[] dpGoodsYN;
    public String[] seq5;
    public String[] happenDate;
    public String[] startDate;
    public String[] endDate;
    public String[] note;
    public String[] stateGubun;
    public String[] punishmentCount;
    public String[] stopGubun;
    public String[] stopDay;
    public String[] stopSayu;
    public String[] punishmentBasicCode;
    public String[] punishmentBasic;
    public String[] dipunishmentBasic;
    public String[] punishmentStart;
    public String[] punishmentEnd;
    public String[] punishmentPeriod;
    public String[] cancelDay;
    public String[] punishmentSayu;
    public String[] punishmentOrgCode;
    public String[] punishmentOrgCodeGubun;
    
    public UM_GOE_ConiC090b() {
        this.sender = new String[] { "", "/gb:Suicod/Header.Details/cc:Message.Sender.Identifier/Identifier.Content" };
        this.receiver = new String[] { "", "/gb:Suicod/Header.Details/cc:Message.Receiver.Identifier/Identifier.Content" };
        this.messFunc = new String[] { "", "/gb:Suicod/Header.Details/cc:Message.Function.Code/Code.Content" };
        this.messCode = new String[] { "", "/gb:Suicod/Header.Details/cc:Message.Type.Identifier/Identifier.Content" };
        this.messName = new String[] { "", "/gb:Suicod/Header.Details/cc:Message.Name/Text.Content" };
        this.messVersion = new String[] { "", "/gb:Suicod/Header.Details/cc:Message.Version.Text/Text.Content" };
        this.messNum = new String[] { "", "/gb:Suicod/Header.Details/cc:Document.Number.Text/Text.Content" };
        this.manageNum = new String[] { "", "/gb:Suicod/Header.Details/cc:Document.ManagementNumber.Text/Text.Content" };
        this.referNum = new String[] { "", "/gb:Suicod/Header.Details/cc:Document.ReferenceNumber.Text/Text.Content" };
        this.title = new String[] { "", "/gb:Suicod/Header.Details/cc:Document.Title.Name/Text.Content" };
        this.saupNo = new String[] { "", "/gb:Suicod/DocList/DocItem/Supplier.Organization.Details/Organization.Identifier/Identifier.Content" };
        this.nationality = new String[] { "", "/gb:Suicod/DocList/DocItem/Supplier.Organization.Details/cc:Nationality.Code/Code.Content" };
        this.sangho = new String[] { "", "/gb:Suicod/DocList/DocItem/Supplier.Organization.Details/Company.Name/Text.Content" };
        this.eSangho = new String[] { "", "/gb:Suicod/DocList/DocItem/Supplier.Organization.Details/Organization.English.Name/Text.Content" };
        this.openDate = new String[] { "", "/gb:Suicod/DocList/DocItem/Business.Open.Date/DateTime.Content" };
        this.bubinOpenDate = new String[] { "", "/gb:Suicod/DocList/DocItem/Corporation.Start.Date/DateTime.Content" };
        this.jobGubun = new String[] { "", "/gb:Suicod/DocList/DocItem/Business.Code/Code.Content" };
        this.makeGubun = new String[] { "", "/gb:Suicod/DocList/DocItem/Manufacturing.Code/Code.Content" };
        this.dpUpjongCode = new String[] { "", "/gb:Suicod/DocList/DocItem/Representation.BisinessType.Code/Code.Content" };
        this.bubinNo = new String[] { "", "/gb:Suicod/DocList/DocItem/Registration.Number.Text/Text.Content" };
        this.comGubun1 = new String[] { "", "/gb:Suicod/DocList/DocItem/Organization.Classfication1.Code/Code.Content" };
        this.comGubun2 = new String[] { "", "/gb:Suicod/DocList/DocItem/Organization.Classfication2.Code/Code.Content" };
        this.comGubunYear = new String[] { "", "/gb:Suicod/DocList/DocItem/Organization.IndicatorYear.Date/DateTime.Content" };
        this.jabon = new String[] { "", "/gb:Suicod/DocList/DocItem/Capital.Amount/Amount.Content" };
        this.employeeNo = new String[] { "", "/gb:Suicod/DocList/DocItem/Employee.Number.Value/Numeric.Content" };
        this.accountDate = new String[] { "", "/gb:Suicod/DocList/DocItem/Recent.Settlement.Date/DateTime.Content" };
        this.zipCode = new String[] { "", "/gb:Suicod/DocList/DocItem/Supplier.Organization.Details/Address.Details/cc:PostCode.Identifier/Identifier.Content" };
        this.localCode = new String[] { "", "/gb:Suicod/DocList/DocItem/Supplier.Organization.Details/Area.Limtation.Code/Code.Name" };
        this.addr = new String[] { "", "/gb:Suicod/DocList/DocItem/Supplier.Organization.Details/Address.Details/cc:Address.Line1.Text/Text.Content" };
        this.restAddr = new String[] { "", "/gb:Suicod/DocList/DocItem/Supplier.Organization.Details/Address.Details/cc:Address.Line2.Text/Text.Content" };
        this.tel = new String[] { "", "/gb:Suicod/DocList/DocItem/Supplier.Organization.Details/Contact.Details/cc:Telephone.Number.Text/Text.Content" };
        this.fax = new String[] { "", "/gb:Suicod/DocList/DocItem/Supplier.Organization.Details/Contact.Details/cc:Fax.Number.Text/Text.Content" };
        this.homepage = new String[] { "", "/gb:Suicod/DocList/DocItem/HomePage.Text/Text.Content" };
        this.exceptYN = new String[] { "", "/gb:Suicod/DocList/DocItem/Factory.Exception.Indicator/Indicator.Content" };
        this.registOkDate = new String[] { "", "/gb:Suicod/DocList/DocItem/Registration.Validity.Date/DateTime.Content" };
        this.registDate = new String[] { "", "/gb:Suicod/DocList/DocItem/Registration.Date/DateTime.Content" };
        this.renewDate = new String[] { "", "/gb:Suicod/DocList/DocItem/Adjust.Date/DateTime.Content" };
        this.dpOkYN = new String[] { "", "/gb:Suicod/DocList/DocItem/Representation.authorization.Indicator/Indicator.Content" };
        this.seq1 = new String[] { "", "/gb:Suicod/DocList/DocItem/LicenList/LicenItem/Line.Number.Value/Numeric.Content" };
        this.licenseNo = new String[] { "", "/gb:Suicod/DocList/DocItem/LicenList/LicenItem/License.Number.Text/Text.Content" };
        this.licenseCode = new String[] { "", "/gb:Suicod/DocList/DocItem/LicenList/LicenItem/License.Code/Code.Content" };
        this.licenseBeginDate = new String[] { "", "/gb:Suicod/DocList/DocItem/LicenList/LicenItem/License.ValidityStart.Date/DateTime.Content" };
        this.licenseEndDate = new String[] { "", "/gb:Suicod/DocList/DocItem/LicenList/LicenItem/License.ValidityEnd.Date/DateTime.Content" };
        this.sigongAccount = new String[] { "", "/gb:Suicod/DocList/DocItem/LicenList/LicenItem/Construcation.AbliltyPar.Amount/Amount.Content" };
        this.peonggaYear = new String[] { "", "/gb:Suicod/DocList/DocItem/LicenList/LicenItem/ParRank.AmountStandardYear.Date/DateTime.Content" };
        this.dpLicenseYN = new String[] { "", "/gb:Suicod/DocList/DocItem/LicenList/LicenItem/Representation.License.Indicator/Indicator.Content" };
        this.seq2 = new String[] { "", "/gb:Suicod/DocList/DocItem/Supplier.Organization.Details/CeoList/CeoItem/Line.Number.Value/Numeric.Content" };
        this.ceoJuminNo = new String[] { "", "/gb:Suicod/DocList/DocItem/Supplier.Organization.Details/CeoList/CeoItem/cc:Organization.CEO.Identifier/Identifier.Content" };
        this.ceoName = new String[] { "", "/gb:Suicod/DocList/DocItem/Supplier.Organization.Details/CeoList/CeoItem/Organization.CEO.Name/Text.Content" };
        this.ceoMail = new String[] { "", "/gb:Suicod/DocList/DocItem/Supplier.Organization.Details/CeoList/CeoItem/Email.Address.Text/Text.Content" };
        this.ceoYN = new String[] { "", "/gb:Suicod/DocList/DocItem/Supplier.Organization.Details/CeoList/CeoItem/Representation.Ceo.Indicator/Indicator.Content" };
        this.ilrunNo = new String[] { "", "/gb:Suicod/DocList/DocItem/FacList/FacItem/Line.Number.Value/Numeric.Content" };
        this.factoryName = new String[] { "", "/gb:Suicod/DocList/DocItem/FacList/FacItem/Factory.Name/Text.Content" };
        this.factoryZipCode = new String[] { "", "/gb:Suicod/DocList/DocItem/FacList/FacItem/Address.Details/cc:PostCode.Identifier/Identifier.Content" };
        this.factoryAddr = new String[] { "", "/gb:Suicod/DocList/DocItem/FacList/FacItem/Address.Details/cc:Address.Line1.Text/Text.Content" };
        this.factoryRestAddr = new String[] { "", "/gb:Suicod/DocList/DocItem/FacList/FacItem/Address.Details/cc:Address.Line2.Text/Text.Content" };
        this.factoryTel = new String[] { "", "/gb:Suicod/DocList/DocItem/FacList/FacItem/Contact.Details/cc:Telephone.Number.Text/Text.Content" };
        this.factoryFax = new String[] { "", "/gb:Suicod/DocList/DocItem/FacList/FacItem/Contact.Details/cc:Fax.Number.Text/Text.Content" };
        this.seq3 = new String[] { "", "/gb:Suicod/DocList/DocItem/RepList/RepItem/Line.Number.Value/Numeric.Content" };
        this.juminNo = new String[] { "", "/gb:Suicod/DocList/DocItem/RepList/RepItem/Employee.Details/Person.Identifier/Identifier.Content" };
        this.name = new String[] { "", "/gb:Suicod/DocList/DocItem/RepList/RepItem/Employee.Details/cc:Employee.Name/Text.Content" };
        this.jobPart = new String[] { "", "/gb:Suicod/DocList/DocItem/RepList/RepItem/Employee.Details/cc:Department.Name/Text.Content" };
        this.dutyName = new String[] { "", "/gb:Suicod/DocList/DocItem/RepList/RepItem/Employee.Details/cc:Employee.Title.Name/Text.Content" };
        this.tel3 = new String[] { "", "/gb:Suicod/DocList/DocItem/RepList/RepItem/Employee.Details/cc:Telephone.Number.Text/Text.Content" };
        this.mail = new String[] { "", "/gb:Suicod/DocList/DocItem/RepList/RepItem/Employee.Details/Email.Address.Text/Text.Content" };
        this.handphone = new String[] { "", "/gb:Suicod/DocList/DocItem/RepList/RepItem/Employee.Details/PCS.Number.Text/Text.Content" };
        this.fax3 = new String[] { "", "/gb:Suicod/DocList/DocItem/RepList/RepItem/Employee.Details/cc:Fax.Number.Text/Text.Content" };
        this.seq4 = new String[] { "", "/gb:Suicod/DocList/DocItem/ManList/ManItem/cc:Line.Number.Value/Numeric.Content" };
        this.goodsNo = new String[] { "", "/gb:Suicod/DocList/DocItem/ManList/ManItem/cc:Item.ClassificationNumber.Identifier/Identifier.Content" };
        this.formNo = new String[] { "", "/gb:Suicod/DocList/DocItem/ManList/ManItem/Form.Approval.Identifier/Identifier.Content" };
        this.formOrg = new String[] { "", "/gb:Suicod/DocList/DocItem/ManList/ManItem/Form.ApprovalOrg.Name/Text.Content" };
        this.formDate = new String[] { "", "/gb:Suicod/DocList/DocItem/ManList/ManItem/Form.Approval.Date/DateTime.Content" };
        this.threeSale = new String[] { "", "/gb:Suicod/DocList/DocItem/ManList/ManItem/Sale.Recent.Amount/Amount.Content" };
        this.makeYN = new String[] { "", "/gb:Suicod/DocList/DocItem/ManList/ManItem/Manufacturing.Indicator/Indicator.Content" };
        this.dpGoodsYN = new String[] { "", "/gb:Suicod/DocList/DocItem/ManList/ManItem/Representation.Item.Indicator/Indicator.Content" };
        this.seq5 = new String[] { "", "/gb:Suicod/DocList/DocItem/CondList/CondItem/cc:Line.Number.Value/Numeric.Content" };
        this.happenDate = new String[] { "", "/gb:Suicod/DocList/DocItem/CondList/CondItem/Origin.Date/DateTime.Content" };
        this.startDate = new String[] { "", "/gb:Suicod/DocList/DocItem/CondList/CondItem/Start.Date/DateTime.Content" };
        this.endDate = new String[] { "", "/gb:Suicod/DocList/DocItem/CondList/CondItem/End.Date/DateTime.Content" };
        this.note = new String[] { "", "/gb:Suicod/DocList/DocItem/CondList/CondItem/General.Note.Text/Text.Content" };
        this.stateGubun = new String[] { "", "/gb:Suicod/DocList/DocItem/CondList/CondItem/Situation.Code/Code.Content" };
        this.punishmentCount = new String[] { "", "/gb:Suicod/DocList/DocItem/RestList/RestItem/cc:Line.Number.Value/Numeric.Content" };
        this.stopGubun = new String[] { "", "/gb:Suicod/DocList/DocItem/RestList/RestItem/Sanction.Details/Suspend.Indicator/Indicator.Content" };
        this.stopDay = new String[] { "", "/gb:Suicod/DocList/DocItem/RestList/RestItem/Sanction.Details/Suspend.Date/DateTime.Content" };
        this.stopSayu = new String[] { "", "/gb:Suicod/DocList/DocItem/RestList/RestItem/Sanction.Details/SuspendReason.Text/Text.Content" };
        this.punishmentBasicCode = new String[] { "", "/gb:Suicod/DocList/DocItem/RestList/RestItem/Sanction.Details/Sanction.Basis.Text/Text.Content" };
        this.punishmentBasic = new String[] { "", "/gb:Suicod/DocList/DocItem/RestList/RestItem/Sanction.Details/Sanction.Basis.Code/Code.Content" };
        this.dipunishmentBasic = new String[] { "", "/gb:Suicod/DocList/DocItem/RestList/RestItem/Sanction.Details/OtherSanction.Basis.Text/Text.Content" };
        this.punishmentStart = new String[] { "", "/gb:Suicod/DocList/DocItem/RestList/RestItem/Sanction.Details/Sanction.Date/DateTime.Content" };
        this.punishmentEnd = new String[] { "", "/gb:Suicod/DocList/DocItem/RestList/RestItem/Sanction.Details/Expiration.Date/DateTime.Content" };
        this.punishmentPeriod = new String[] { "", "/gb:Suicod/DocList/DocItem/RestList/RestItem/Sanction.Details/Sanction.Periode.Text/Text.Content" };
        this.cancelDay = new String[] { "", "/gb:Suicod/DocList/DocItem/RestList/RestItem/Sanction.Details/Contract.Cancel.Date/DateTime.Content" };
        this.punishmentSayu = new String[] { "", "/gb:Suicod/DocList/DocItem/RestList/RestItem/Sanction.Details/Sanction.Reason.Code/Code.Content" };
        this.punishmentOrgCode = new String[] { "", "/gb:Suicod/DocList/DocItem/RestList/RestItem/Sanction.Details/Sanction.Organization.Code/Code.Content" };
        this.punishmentOrgCodeGubun = new String[] { "", "/gb:Suicod/DocList/DocItem/RestList/RestItem/Sanction.Details/Sanction.GovernmentOffice.Code/Code.Content" };
    }
    
    public void UM_GOE_ConiC090b() {
    }
}
