// 
// Decompiled by Procyon v0.5.30
// 

package servlets;

public class UM_ADV_ConrA020c
{
    public String[] sender_id;
    public String[] receiver_id;
    public String[] doc_function;
    public String[] doc_cd;
    public String[] doc_nm;
    public String[] edoc_ver;
    public String[] doc_no;
    public String[] reference_no;
    public String[] doc_sum;
    public String[] transmit_no;
    public String[] biz_reg_no;
    public String[] nationality;
    public String[] nationality_nm;
    public String[] biz_nm;
    public String[] biz_en_nm;
    public String[] biz_en_sort_nm;
    public String[] commentcement_dt;
    public String[] establish_dt;
    public String[] biz_cls;
    public String[] product_cls;
    public String[] mast_industry_cd_std;
    public String[] mast_inductry_cd_nm;
    public String[] corp_reg_no;
    public String[] biz_cls_1;
    public String[] biz_cls_2;
    public String[] biz_cls_year;
    public String[] capital;
    public String[] employee_count_;
    public String[] lat_settle_dt;
    public String[] zip_cd;
    public String[] area_cd;
    public String[] area_nm;
    public String[] addr;
    public String[] addr_detail;
    public String[] phone_no;
    public String[] fax;
    public String[] homepage;
    public String[] special_good_yn;
    public String[] cert;
    public String[] contr_rela_yn;
    public String[] serial_no_1;
    public String[] rerp_ident_no;
    public String[] repr_nm;
    public String[] repr_mail;
    public String[] mast_repr_yn;
    public String[] repr_mobile;
    public String[] repr_cls;
    public String[] branch_serial_no;
    public String[] branch_biz_reg_no;
    public String[] branch_biz_nm;
    public String[] branch_ared_cd;
    public String[] branch_area_nm;
    public String[] branch_regist_yn;
    public String[] branch_zip_cd;
    public String[] branch_add;
    public String[] branch_add2;
    public String[] branch_phone;
    public String[] branch_fax;
    public String[] branch_repr_ident_no;
    public String[] branch_rept_nm;
    public String[] serial_no;
    public String[] fac_nm;
    public String[] fac_zip_cd;
    public String[] fac_add;
    public String[] fac_add2;
    public String[] fac_phone;
    public String[] fac_fax;
    public String[] fac_rent_yn;
    public String[] fac_rent_start_dt;
    public String[] fac_rent_end_dt;
    public String[] serial_no_2;
    public String[] goods_cls_nm;
    public String[] add;
    public String[] goods_cls_no;
    public String[] income_3year;
    public String[] direct_product_yn;
    public String[] direct_product_fm;
    public String[] mast_goods_yn;
    public String[] mast_goods_fm;
    public String[] serial_no5;
    public String[] goods_cls_nm1;
    public String[] add1;
    public String[] goods_cls_no1;
    public String[] imcome_3year1;
    public String[] permit_no1;
    public String[] permit_institu1;
    public String[] permit_dt1;
    public String[] direct_product_yn1;
    public String[] direct_product_fm1;
    public String[] mast_goods_yn1;
    public String[] mast_goods_fm1;
    public String[] direct_product_doc;
    public String[] avail_period_start_dt;
    public String[] avail_period_end_dt;
    public String[] industry_cls_cd;
    public String[] issua_institu;
    public String[] doc_nm1;
    public String[] serial_no3;
    public String[] license_no;
    public String[] license_cd;
    public String[] license_nm;
    public String[] license_issued_dt;
    public String[] license_expiry_dt;
    public String[] const_abil_eval_amt;
    public String[] eval_std_year;
    public String[] mast_license_yn;
    public String[] mast_license_fm;
    public String[] serial_no4;
    public String[] ident_no;
    public String[] nm;
    public String[] depart;
    public String[] position;
    public String[] agent_phone;
    public String[] E_MAIL;
    public String[] mobile;
    public String[] FAX;
    public String[] agent_yn;
    public String[] request_change_cls;
    public String[] request_dt;
    public String[] progress_st;
    public String[] manage_reason;
    public String[] xml_path;
    public String[] permit_branch;
    public String[] permit_branch_nm;
    public String[] name_ca;
    public String[] cmnd_ca;
    public String[] id_ca;
    
    public UM_ADV_ConrA020c() {
        this.sender_id = new String[] { "", "/gb:Gsacid/Header.Details/cc:Message.Sender.Identifier/Identifier.Content" };
        this.receiver_id = new String[] { "", "/gb:Gsacid/Header.Details/cc:Message.Receiver.Identifier/Identifier.Content" };
        this.doc_function = new String[] { "", "/gb:Gsacid/Header.Details/cc:Message.Function.Code/Code.Content" };
        this.doc_cd = new String[] { "", "/gb:Gsacid/Header.Details/cc:Message.Type.Identifier/Identifier.Content" };
        this.doc_nm = new String[] { "", "/gb:Gsacid/Header.Details/cc:Message.Name/Text.Content" };
        this.edoc_ver = new String[] { "", "/gb:Gsacid/Header.Details/cc:Message.Version.Text/Text.Content" };
        this.doc_no = new String[] { "", "/gb:Gsacid/Header.Details/cc:Document.Number.Text/Text.Content" };
        this.reference_no = new String[] { "", "/gb:Gsacid/Header.Details/cc:Document.ReferenceNumber.Text/Text.Content" };
        this.doc_sum = new String[] { "", "/gb:Gsacid/Header.Details/cc:Document.Title.Name/Text.Content" };
        this.transmit_no = new String[] { "", "/gb:Gsacid/Header.Details/cc:Document.ManagementNumber.Text/Text.Content" };
        this.biz_reg_no = new String[] { "", "/gb:Gsacid/Supplier.Organization.Details/Organization.Identifier/Identifier.Content" };
        this.nationality = new String[] { "", "/gb:Gsacid/Supplier.Organization.Details/Nationality.Code/Code.Content" };
        this.nationality_nm = new String[] { "", "/gb:Gsacid/Supplier.Organization.Details/Nationality.Code/Code.Name" };
        this.biz_nm = new String[] { "", "/gb:Gsacid/Supplier.Organization.Details/Company.Name/Text.Content" };
        this.biz_en_nm = new String[] { "", "/gb:Gsacid/Supplier.Organization.Details/Organization.English.Name/Text.Content" };
        this.biz_en_sort_nm = new String[] { "", "/gb:Gsacid/Supplier.Organization.Details/Organization.InformalEnglish.Name/Text.Content" };
        this.commentcement_dt = new String[] { "", "/gb:Gsacid/Business.Open.Date/DateTime.Content" };
        this.establish_dt = new String[] { "", "/gb:Gsacid/Corporation.Start.Date/DateTime.Content" };
        this.biz_cls = new String[] { "", "/gb:Gsacid/Business.Code/Code.Content" };
        this.product_cls = new String[] { "", "/gb:Gsacid/Manufacturing.Code/Code.Content" };
        this.mast_industry_cd_std = new String[] { "", "/gb:Gsacid/BisinessType.Code/Code.Content" };
        this.mast_inductry_cd_nm = new String[] { "", "/gb:Gsacid/BisinessType.Code/Code.Name" };
        this.corp_reg_no = new String[] { "", "/gb:Gsacid/Registration.Number.Text/Text.Content" };
        this.biz_cls_1 = new String[] { "", "/gb:Gsacid/Organization.Classfication1.Code/Code.Content" };
        this.biz_cls_2 = new String[] { "", "/gb:Gsacid/Organization.Classfication2.Code/Code.Content" };
        this.biz_cls_year = new String[] { "", "/gb:Gsacid/Organization.IndicatorYear.Date/DateTime.Content" };
        this.capital = new String[] { "", "/gb:Gsacid/Capital.Amount/Amount.Content" };
        this.employee_count_ = new String[] { "", "/gb:Gsacid/Employee.Number.Value/Numeric.Content" };
        this.lat_settle_dt = new String[] { "", "/gb:Gsacid/Recent.Settlement.Date/DateTime.Content" };
        this.zip_cd = new String[] { "", "/gb:Gsacid/Supplier.Organization.Details/Address.Details/cc:PostCode.Identifier/Identifier.Content" };
        this.area_cd = new String[] { "", "/gb:Gsacid/Supplier.Organization.Details/Address.Details/cc:PostCode.Identifier/Identifier.Content" };
        this.area_nm = new String[] { "", "/gb:Gsacid/Supplier.Organization.Details/Area.Limtation.Code/Code.Name" };
        this.addr = new String[] { "", "/gb:Gsacid/Supplier.Organization.Details/Address.Details/cc:Address.Line1.Text/Text.Content" };
        this.addr_detail = new String[] { "", "/gb:Gsacid/Supplier.Organization.Details/Address.Details/cc:Address.Line2.Text/Text.Content" };
        this.phone_no = new String[] { "", "/gb:Gsacid/Supplier.Organization.Details/Contact.Details/cc:Telephone.Number.Text/Text.Content" };
        this.fax = new String[] { "", "/gb:Gsacid/Supplier.Organization.Details/Contact.Details/cc:Fax.Number.Text/Text.Content" };
        this.homepage = new String[] { "", "/gb:Gsacid/HomePage.Text/Text.Content" };
        this.special_good_yn = new String[] { "", "/gb:Gsacid/Factory.Exception.Indicator/Indicator.Content" };
        this.cert = new String[] { "", "/gb:Gsacid/Server.Key.Text/Text.Content" };
        this.contr_rela_yn = new String[] { "", "/gb:Gsacid/cc:Integrity.ContractPerformance.Indicator/Indicator.Content" };
        this.serial_no_1 = new String[] { "", "/gb:Gsacid/Supplier.Organization.Details/CeoList/CeoItem/cc:Line.Number.Value/Numeric.Content" };
        this.rerp_ident_no = new String[] { "", "/gb:Gsacid/Supplier.Organization.Details/CeoList/CeoItem/cc:Organization.CEO.Identifier/Identifier.Content" };
        this.repr_nm = new String[] { "", "/gb:Gsacid/Supplier.Organization.Details/CeoList/CeoItem/Organization.CEO.Name/Text.Content" };
        this.repr_mail = new String[] { "", "/gb:Gsacid/Supplier.Organization.Details/CeoList/CeoItem/Email.Address.Text/Text.Content" };
        this.mast_repr_yn = new String[] { "", "/gb:Gsacid/Supplier.Organization.Details/CeoList/CeoItem/Representation.Ceo.Indicator/Indicator.Content" };
        this.repr_mobile = new String[] { "", "/gb:Gsacid/Supplier.Organization.Details/CeoList/CeoItem/cc:PCS.Number.Text/Text.Content" };
        this.repr_cls = new String[] { "", "/gb:Gsacid/Supplier.Organization.Details/CeoList/CeoItem/cc:CEO.Type.Code/Code.Content" };
        this.branch_serial_no = new String[] { "", "/gb:Gsacid/BranchList/BranchItem/cc:Line.Number.Value/Numeric.Content" };
        this.branch_biz_reg_no = new String[] { "", "/gb:Gsacid/BranchList/BranchItem/BranchOffice.Details/cc:Organization.Identifier/Identifier.Content" };
        this.branch_biz_nm = new String[] { "", "/gb:Gsacid/BranchList/BranchItem/BranchOffice.Details/cc:Company.Name/Text.Content" };
        this.branch_ared_cd = new String[] { "", "/gb:Gsacid/BranchList/BranchItem/BranchOffice.Details/cc:Area.Limtation.Code/Code.Content" };
        this.branch_area_nm = new String[] { "", "/gb:Gsacid/BranchList/BranchItem/BranchOffice.Details/cc:Area.Limtation.Code/Code.Name" };
        this.branch_regist_yn = new String[] { "", "/gb:Gsacid/BranchList/BranchItem/BranchOffice.Details/cc:Registration.Cancel.Indicator/Indicator.Content" };
        this.branch_zip_cd = new String[] { "", "/gb:Gsacid/BranchList/BranchItem/BranchOffice.Details/Address.Details/cc:PostCode.Identifier/Identifier.Content" };
        this.branch_add = new String[] { "", "/gb:Gsacid/BranchList/BranchItem/BranchOffice.Details/Address.Details/cc:Address.Line1.Text/Text.Content" };
        this.branch_add2 = new String[] { "", "/gb:Gsacid/BranchList/BranchItem/BranchOffice.Details/Address.Details/cc:Address.Line2.Text/Text.Content" };
        this.branch_phone = new String[] { "", "/gb:Gsacid/BranchList/BranchItem/BranchOffice.Details/Contact.Details/cc:Telephone.Number.Text/Text.Content" };
        this.branch_fax = new String[] { "", "/gb:Gsacid/BranchList/BranchItem/BranchOffice.Details/Contact.Details/cc:Fax.Number.Text/Text.Content" };
        this.branch_repr_ident_no = new String[] { "", "/gb:Gsacid/BranchList/BranchItem/BranchOffice.Details/CEO.Details/cc:Organization.CEO.Identifier/Identifier.Content" };
        this.branch_rept_nm = new String[] { "", "/gb:Gsacid/BranchList/BranchItem/BranchOffice.Details/CEO.Details/cc:Organization.CEO.Name/Text.Content" };
        this.serial_no = new String[] { "", "/gb:Gsacid/FacList/FacItem/cc:Line.Number.Value/Numeric.Content" };
        this.fac_nm = new String[] { "", "/gb:Gsacid/FacList/FacItem/Factory.Name/Text.Content" };
        this.fac_zip_cd = new String[] { "", "/gb:Gsacid/FacList/FacItem/Address.Details/cc:PostCode.Identifier/Identifier.Content" };
        this.fac_add = new String[] { "", "/gb:Gsacid/FacList/FacItem/Address.Details/cc:Address.Line1.Text/Text.Content" };
        this.fac_add2 = new String[] { "", "/gb:Gsacid/FacList/FacItem/Address.Details/cc:Address.Line2.Text/Text.Content" };
        this.fac_phone = new String[] { "", "/gb:Gsacid/FacList/FacItem/Contact.Details/cc:Telephone.Number.Text/Text.Content" };
        this.fac_fax = new String[] { "", "/gb:Gsacid/FacList/FacItem/Contact.Details/cc:Fax.Number.Text/Text.Content" };
        this.fac_rent_yn = new String[] { "", "/gb:Gsacid/FacList/FacItem/cc:Own.Lease.Indicator/Indicator.Content" };
        this.fac_rent_start_dt = new String[] { "", "/gb:Gsacid/FacList/FacItem/cc:Lease.Start.Date/DateTime.Content" };
        this.fac_rent_end_dt = new String[] { "", "/gb:Gsacid/FacList/FacItem/cc:Lease.Complete.Date/DateTime.Content" };
        this.serial_no_2 = new String[] { "", "/gb:Gsacid/SupList/SupItem/cc:Line.Number.Value/Numeric.Content" };
        this.goods_cls_nm = new String[] { "", "/gb:Gsacid/SupList/SupItem/cc:Item.Name/Text.Content" };
        this.add = new String[] { "", "/gb:Gsacid/SupList/SupItem/cc:Item.Additional.Identifier/Identifier.Content" };
        this.goods_cls_no = new String[] { "", "/gb:Gsacid/SupList/SupItem/cc:Item.ClassificationNumber.Identifier/Identifier.Content" };
        this.income_3year = new String[] { "", "/gb:Gsacid/SupList/SupItem/Sale.Recent.Amount/Amount.Content" };
        this.direct_product_yn = new String[] { "", "/gb:Gsacid/SupList/SupItem/Manufacturing.Indicator/Indicator.Content" };
        this.direct_product_fm = new String[] { "", "/gb:Gsacid/SupList/SupItem/Manufacturing.Indicator/Indicator.Format.Text" };
        this.mast_goods_yn = new String[] { "", "/gb:Gsacid/SupList/SupItem/Representation.Item.Indicator/Indicator.Content" };
        this.mast_goods_fm = new String[] { "", "/gb:Gsacid/SupList/SupItem/Representation.Item.Indicator/Indicator.Format.Text" };
        this.serial_no5 = new String[] { "", "/gb:Gsacid/ManList/ManItem/cc:Line.Number.Value/Numeric.Content" };
        this.goods_cls_nm1 = new String[] { "", "/gb:Gsacid/ManList/ManItem/cc:Item.Name/Text.Content" };
        this.add1 = new String[] { "", "/gb:Gsacid/ManList/ManItem/cc:Item.Additional.Identifier/Identifier.Content" };
        this.goods_cls_no1 = new String[] { "", "/gb:Gsacid/ManList/ManItem/cc:Item.ClassificationNumber.Identifier/Identifier.Content" };
        this.imcome_3year1 = new String[] { "", "/gb:Gsacid/ManList/ManItem/Sale.Recent.Amount/Amount.Content" };
        this.permit_no1 = new String[] { "", "/gb:Gsacid/ManList/ManItem/Form.Approval.Identifier/Identifier.Content" };
        this.permit_institu1 = new String[] { "", "/gb:Gsacid/ManList/ManItem/Form.ApprovalOrg.Name/Text.Content" };
        this.permit_dt1 = new String[] { "", "/gb:Gsacid/ManList/ManItem/Form.Approval.Date/DateTime.Content" };
        this.direct_product_yn1 = new String[] { "", "/gb:Gsacid/ManList/ManItem/Manufacturing.Indicator/Indicator.Content" };
        this.direct_product_fm1 = new String[] { "", "/gb:Gsacid/ManList/ManItem/Manufacturing.Indicator/Indicator.Format.Text" };
        this.mast_goods_yn1 = new String[] { "", "/gb:Gsacid/ManList/ManItem/Representation.Item.Indicator/Indicator.Content" };
        this.mast_goods_fm1 = new String[] { "", "/gb:Gsacid/ManList/ManItem/Representation.Item.Indicator/Indicator.Format.Text" };
        this.direct_product_doc = new String[] { "", "/gb:Gsacid/ManList/ManItem/Manufacturing.Details/cc:Production.Certification.Code/Code.Content" };
        this.avail_period_start_dt = new String[] { "", "/gb:Gsacid/ManList/ManItem/Manufacturing.Details/cc:Validity.Start.Date/DateTime.Content" };
        this.avail_period_end_dt = new String[] { "", "/gb:Gsacid/ManList/ManItem/Manufacturing.Details/cc:Validity.End.Date/DateTime.Content" };
        this.industry_cls_cd = new String[] { "", "/gb:Gsacid/ManList/ManItem/Manufacturing.Details/cc:StandardIndustry.Classification.Code/Code.Content" };
        this.issua_institu = new String[] { "", "/gb:Gsacid/ManList/ManItem/Manufacturing.Details/cc:Organization.Name/Text.Content" };
        this.doc_nm1 = new String[] { "", "/gb:Gsacid/ManList/ManItem/Manufacturing.Details/cc:Certificate.Name/Text.Content" };
        this.serial_no3 = new String[] { "", "/gb:Gsacid/LicenList/LicenItem/cc:Line.Number.Value/Numeric.Content" };
        this.license_no = new String[] { "", "/gb:Gsacid/LicenList/LicenItem/License.Number.Text/Text.Content" };
        this.license_cd = new String[] { "", "/gb:Gsacid/LicenList/LicenItem/License.Code/Code.Content" };
        this.license_nm = new String[] { "", "/gb:Gsacid/LicenList/LicenItem/License.Code/Code.Name" };
        this.license_issued_dt = new String[] { "", "/gb:Gsacid/LicenList/LicenItem/License.ValidityStart.Date/DateTime.Content" };
        this.license_expiry_dt = new String[] { "", "/gb:Gsacid/LicenList/LicenItem/cc:License.ValidityEnd.Date/DateTime.Content" };
        this.const_abil_eval_amt = new String[] { "", "/gb:Gsacid/LicenList/LicenItem/Construcation.AbliltyPar.Amount/Amount.Content" };
        this.eval_std_year = new String[] { "", "/gb:Gsacid/LicenList/LicenItem/ParRank.AmountStandardYear.Date/DateTime.Content" };
        this.mast_license_yn = new String[] { "", "/gb:Gsacid/LicenList/LicenItem/Representation.License.Indicator/Indicator.Content" };
        this.mast_license_fm = new String[] { "", "/gb:Gsacid/LicenList/LicenItem/Representation.License.Indicator/Indicator.Format.Text" };
        this.serial_no4 = new String[] { "", "/gb:Gsacid/RepList/RepItem/cc:Line.Number.Value/Numeric.Content" };
        this.ident_no = new String[] { "", "/gb:Gsacid/RepList/RepItem/Employee.Details/cc:Person.Identifier/Identifier.Content" };
        this.nm = new String[] { "", "/gb:Gsacid/RepList/RepItem/Employee.Details/cc:Employee.Name/Text.Content" };
        this.depart = new String[] { "", "/gb:Gsacid/RepList/RepItem/Employee.Details/cc:Department.Name/Text.Content" };
        this.position = new String[] { "", "/gb:Gsacid/RepList/RepItem/Employee.Details/Employee.Title.Name/Text.Content" };
        this.agent_phone = new String[] { "", "/gb:Gsacid/RepList/RepItem/Employee.Details/cc:Telephone.Number.Text/Text.Content" };
        this.E_MAIL = new String[] { "", "/gb:Gsacid/RepList/RepItem/Employee.Details/cc:Email.Address.Text/Text.Content" };
        this.mobile = new String[] { "", "/gb:Gsacid/RepList/RepItem/Employee.Details/PCS.Number.Text/Text.Content" };
        this.FAX = new String[] { "", "/gb:Gsacid/RepList/RepItem/Employee.Details/cc:Fax.Number.Text/Text.Content" };
        this.agent_yn = new String[] { "", "/gb:Gsacid/RepList/RepItem/Employee.Details/cc:BiddingAgent.Confirmation.Indicator/Indicator.Content" };
        this.request_change_cls = new String[] { "", "/gb:Gsacid/" };
        this.request_dt = new String[] { "", "/gb:Gsacid/" };
        this.progress_st = new String[] { "", "/gb:Gsacid/Processing.State.Text/Text.Content" };
        this.manage_reason = new String[] { "", "/gb:Gsacid/Processing.Reason.Text/Text.Content" };
        this.xml_path = new String[] { "", "/gb:Gsacid/" };
        this.permit_branch = new String[] { "", "/gb:Gsacid/Branch.Code/Code.Content" };
        this.permit_branch_nm = new String[] { "", "/gb:Gsacid/Branch.Code/Code.Name" };
        this.name_ca = new String[] { "", "/CA/name" };
        this.cmnd_ca = new String[] { "", "/CA/cmnd" };
        this.id_ca = new String[] { "", "/CA/id" };
    }
    
    public void UM_ADV_ConrA020c() {
    }
}
